# Generated by Django 4.1 on 2022-11-01 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0002_answer_question_delete_forum_answer_question_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer", old_name="body", new_name="answers",
        ),
        migrations.RenameField(
            model_name="question", old_name="body", new_name="question",
        ),
    ]
