# Generated by Django 4.1 on 2022-11-01 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0003_rename_body_answer_answers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer", old_name="answers", new_name="body",
        ),
        migrations.RenameField(
            model_name="question", old_name="question", new_name="body",
        ),
    ]
