# Generated by Django 4.1 on 2022-11-02 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0005_remove_answer_parent_remove_answer_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="answer", name="question",),
    ]
