# Generated by Django 4.1 on 2022-11-02 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_remove_answer_updated_at_remove_question_updated_at'),
        ('forum', '0006_remove_answer_question'),
    ]

    operations = [
    ]
