# Generated by Django 4.1 on 2022-11-02 17:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vouchername", models.TextField(max_length=50)),
                ("voucherbody", models.TextField(max_length=100)),
                ("requiredpoin", models.IntegerField(default=0)),
                ("redeemed", models.IntegerField(default=0)),
                ("is_redeemed", models.BooleanField(default=False)),
                ("area_required", models.TextField(default="")),
                ("expired_date", models.DateField(default=datetime.date.today)),
                ("available_voucher", models.IntegerField(default=0)),
                (
                    "voucherbank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voucher_bank",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
