# Generated by Django 4.1 on 2022-10-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
