# Generated by Django 4.1 on 2022-10-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('jenis', models.CharField(max_length=15)),
                ('berat', models.IntegerField(null=True)),
                ('poin', models.IntegerField(null=True)),
            ],
        ),
    ]
